name: Tigo Status

on:
  schedule:
    # Runs at 12am IST
    - cron: '10 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_PROJECTS: "TRUE"
